### ISSUE TITLE
Cannot find any context of [loop] among open contexts.

### ISSUE THREAD

**Issue by jurnix** [mbdevpl/open-fortran-parser-xml#1]
I apply the java xml module with a part of my code with the following error:

ajornet@lsce3044:~/projects/open-fortran-parser-xml$ java fortran.ofp.FrontEnd --class fortran.ofp.XMLPrinter --output output.xml --verbosity 0 ../MICT/src_stomate/stomate.f90 
Cannot find any context of [loop] among open contexts.
Current context hierarchy (innermost first) is:
  statement
  body
  if
  body
  subroutine
  members
  module
  file
  ofp
java.lang.RuntimeException: Aborting construction of the AST.
	at fortran.ofp.XMLPrinter.cleanUpAfterError(XMLPrinter.java:2268)
	at fortran.ofp.XMLPrinter.contextFind(XMLPrinter.java:151)
	at fortran.ofp.XMLPrinter.setAttribute(XMLPrinter.java:305)
	at fortran.ofp.XMLPrinter.loop_control(XMLPrinter.java:1644)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.loop_control(FortranParserExtras_FortranParser08.java:25507)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.do_stmt(FortranParserExtras_FortranParser08.java:26778)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.block_do_construct(FortranParserExtras_FortranParser08.java:26646)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.do_construct(FortranParserExtras_FortranParser08.java:26616)
	at fortran.ofp.parser.java.FortranParserExtras.do_construct(FortranParserExtras.java:2855)
	at fortran.ofp.parser.java.FortranParserExtras.executable_construct(FortranParserExtras.java:630)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.execution_part_construct(FortranParserExtras_FortranParser08.java:1002)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.block(FortranParserExtras_FortranParser08.java:22405)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.if_construct(FortranParserExtras_FortranParser08.java:22451)
	at fortran.ofp.parser.java.FortranParserExtras.if_construct(FortranParserExtras.java:2979)
	at fortran.ofp.parser.java.FortranParserExtras.executable_construct(FortranParserExtras.java:652)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.execution_part_construct(FortranParserExtras_FortranParser08.java:1002)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.execution_part(FortranParserExtras_FortranParser08.java:803)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.subroutine_subprogram(FortranParserExtras_FortranParser08.java:39720)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.module_subprogram(FortranParserExtras_FortranParser08.java:34463)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.module_subprogram_part(FortranParserExtras_FortranParser08.java:34380)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.module(FortranParserExtras_FortranParser08.java:33938)
	at fortran.ofp.parser.java.FortranParserExtras.module(FortranParserExtras.java:2930)
	at fortran.ofp.FrontEnd.parseModule(FrontEnd.java:120)
	at fortran.ofp.FrontEnd.parseProgramUnit(FrontEnd.java:199)
	at fortran.ofp.FrontEnd.call(FrontEnd.java:400)
	at fortran.ofp.FrontEnd.main(FrontEnd.java:349)

The code compiles and it runs.
I Also tried it without the xml output. There is no error. So it seems to be related to open-parser-fortran-xml. 

I have uploaded the code: https://pastebin.com/y0CcZr1y

**Comment by jurnix** [comment]
It seems DO WHILE structures have some isse

**Comment by mbdevpl** [comment]
Yes, indeed. The current implementation is VERY experimental, and supports only a VERY limited subset of Fortran.

**Comment by mbdevpl** [comment]
However, I've added the file you attached to my tentative list of parser compatibility tests.

If I may ask... What/who is the target consumer of the XML AST in your case?

**Comment by jurnix** [comment]
I am not sure I correctly understood your question. But I do work as a software engineer for the Orchidee model. A land surface vegetation model.  The model site: https://forge.ipsl.jussieu.fr/orchidee/
Our code is somehow big and its becoming difficult to manage (100k lines). So I am planning/trying to use a tool like this to analyse and/or refactor some code. Python preferably. 

Is it fine to you whether I report more issues? I have another one on the list.

**Comment by mbdevpl** [comment]
Ah, I see. That's exactly the workflow which this tool is aimed to be a part of: maintenance of scientific code.

Certainly, please report any issues you encounter! This will give me much better view of what is actually problematic for the current implementation. And this way I'm bound to get down to fixing those issues at some point :)

However, I must add, that fixing the issues with Fortran XML AST generator is just the start, because to actually maintain/refactor code this way, I'll have to publish my two-way Python/Fortran transpiler. I'm planning to do this, but it's still not ready...

**Comment by jurnix** [comment]
That's cool. I will definitely take advantage of this AST once the whole code can be parsed.

Good job! :-)

**Comment by mbdevpl** [comment]
The file in question (`stomate.f90`) is now being parsed without errors.
