### ISSUE TITLE
NullPointerException in FortranParser2008.initialize

### ISSUE THREAD

**Issue by memmett** [mbdevpl/open-fortran-parser-xml#10]
Hi and thanks for this!

I am getting the following error
```
$ java fortran.ofp.FrontEnd --class fortran.ofp.XMLPrinter --output output.xml --verbosity 100 ~/test.f90
java.lang.reflect.InvocationTargetException
Exception in thread "main" java.lang.NullPointerException
	at fortran.ofp.parser.java.FortranParser2008.initialize(FortranParser2008.java:366)
	at fortran.ofp.FrontEnd.<init>(FrontEnd.java:105)
	at fortran.ofp.FrontEnd.main(FrontEnd.java:368)
```
Here is my Fortran file:
```
module foo
contains
  subroutine foo(i)
    integer, intent(inout) :: i
    i = 1
  end subroutine foo
end module foo
```

I am using
```
$ java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)
```
on Ubuntu.

Any ideas?  I will try to get a Java debugger running.

**Comment by memmett** [comment]
My bad, I forgot to include `commons-cli-1.4.jar` in my CLASSPATH.
