### ISSUE TITLE
Implied loop

### ISSUE THREAD

**Issue by jurnix** [mbdevpl/open-fortran-parser-xml#2]
The error message:

Cannot find any context of [output] among open contexts.
Current context hierarchy (innermost first) is:
  input
  inputs
  statement
  body
  if
  body
  if
  body
  subroutine
  members
  module
  file
  ofp
java.lang.RuntimeException: Aborting construction of the AST.
	at fortran.ofp.XMLPrinter.cleanUpAfterError(XMLPrinter.java:2268)
	at fortran.ofp.XMLPrinter.contextFind(XMLPrinter.java:151)
	at fortran.ofp.XMLPrinter.contextClose(XMLPrinter.java:196)
	at fortran.ofp.XMLPrinter.output_item(XMLPrinter.java:1791)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.output_item(FortranParserExtras_FortranParser08.java:31230)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.io_implied_do_object(FortranParserExtras_FortranParser08.java:31360)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.io_implied_do(FortranParserExtras_FortranParser08.java:31324)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.input_item(FortranParserExtras_FortranParser08.java:31100)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.input_item_list(FortranParserExtras_FortranParser08.java:31138)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.read_stmt(FortranParserExtras_FortranParser08.java:30481)
	at fortran.ofp.parser.java.FortranParserExtras.read_stmt(FortranParserExtras.java:2669)
	at fortran.ofp.parser.java.FortranParserExtras.action_stmt(FortranParserExtras.java:941)
	at fortran.ofp.parser.java.FortranParserExtras.executable_construct(FortranParserExtras.java:575)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.execution_part_construct(FortranParserExtras_FortranParser08.java:1002)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.block(FortranParserExtras_FortranParser08.java:22405)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.if_construct(FortranParserExtras_FortranParser08.java:22451)
	at fortran.ofp.parser.java.FortranParserExtras.if_construct(FortranParserExtras.java:2979)
	at fortran.ofp.parser.java.FortranParserExtras.executable_construct(FortranParserExtras.java:652)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.execution_part_construct(FortranParserExtras_FortranParser08.java:1002)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.block(FortranParserExtras_FortranParser08.java:22405)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.if_construct(FortranParserExtras_FortranParser08.java:22451)
	at fortran.ofp.parser.java.FortranParserExtras.if_construct(FortranParserExtras.java:2979)
	at fortran.ofp.parser.java.FortranParserExtras.executable_construct(FortranParserExtras.java:652)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.execution_part_construct(FortranParserExtras_FortranParser08.java:1002)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.execution_part(FortranParserExtras_FortranParser08.java:803)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.subroutine_subprogram(FortranParserExtras_FortranParser08.java:39720)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.module_subprogram(FortranParserExtras_FortranParser08.java:34463)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.module_subprogram_part(FortranParserExtras_FortranParser08.java:34380)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.module(FortranParserExtras_FortranParser08.java:33938)
	at fortran.ofp.parser.java.FortranParserExtras.module(FortranParserExtras.java:2930)
	at fortran.ofp.FrontEnd.parseModule(FrontEnd.java:120)
	at fortran.ofp.FrontEnd.parseProgramUnit(FrontEnd.java:199)
	at fortran.ofp.FrontEnd.call(FrontEnd.java:400)
	at fortran.ofp.FrontEnd.main(FrontEnd.java:349)

Part of the code where it fails:

3840         READ(61, *, iostat = ier) Pyoung_t
3841         READ(61, *, iostat = ier) Wcalfborn_t
3842       IF ((type_animal.EQ.1).OR.(type_animal.EQ.2)) THEN
3843         READ(61, *, iostat = ier) (MPwmax_t(h),h=1,2)                                                                                             
3844       ELSE
3845         READ(61, *, iostat = ier) MPwmax_t(1)
3846       ENDIF

The source code for this specific file:
https://pastebin.com/BFLQGT9K

**Comment by mbdevpl** [comment]
Thank you for reporting! Indeed, the implied do syntax of kind `(MPwmax_t(h),h=1,2)` is not handled correctly. However, it's one of the things I'm working on today :)
