### ISSUE TITLE
loop + if statement + global variable

### ISSUE THREAD

**Issue by jurnix** [mbdevpl/open-fortran-parser-xml#3]
```
java fortran.ofp.FrontEnd --class fortran.ofp.XMLPrinter --output tree.xml --verbosity 100 src_global/grid.f90 
Cannot rename current context from 'statement' to 'if' because it has unexpected name 'name'.
java.lang.RuntimeException: Aborting construction of the AST.
	at fortran.ofp.XMLPrinter.cleanUpAfterError(XMLPrinter.java:2268)
	at fortran.ofp.XMLPrinter.contextRename(XMLPrinter.java:165)
	at fortran.ofp.XMLPrinter.if_then_stmt(XMLPrinter.java:1437)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.if_then_stmt(FortranParserExtras_FortranParser08.java:22659)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.if_construct(FortranParserExtras_FortranParser08.java:22446)
	at fortran.ofp.parser.java.FortranParserExtras.if_construct(FortranParserExtras.java:2979)
	at fortran.ofp.parser.java.FortranParserExtras.executable_construct(FortranParserExtras.java:652)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.execution_part_construct(FortranParserExtras_FortranParser08.java:1002)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.block(FortranParserExtras_FortranParser08.java:22405)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.block_do_construct(FortranParserExtras_FortranParser08.java:26651)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.do_construct(FortranParserExtras_FortranParser08.java:26616)
	at fortran.ofp.parser.java.FortranParserExtras.do_construct(FortranParserExtras.java:2855)
	at fortran.ofp.parser.java.FortranParserExtras.executable_construct(FortranParserExtras.java:630)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.execution_part_construct(FortranParserExtras_FortranParser08.java:1002)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.block(FortranParserExtras_FortranParser08.java:22405)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.block_do_construct(FortranParserExtras_FortranParser08.java:26651)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.do_construct(FortranParserExtras_FortranParser08.java:26616)
	at fortran.ofp.parser.java.FortranParserExtras.do_construct(FortranParserExtras.java:2855)
	at fortran.ofp.parser.java.FortranParserExtras.executable_construct(FortranParserExtras.java:630)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.execution_part_construct(FortranParserExtras_FortranParser08.java:1002)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.execution_part(FortranParserExtras_FortranParser08.java:803)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.subroutine_subprogram(FortranParserExtras_FortranParser08.java:39720)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.module_subprogram(FortranParserExtras_FortranParser08.java:34463)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.module_subprogram_part(FortranParserExtras_FortranParser08.java:34380)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.module(FortranParserExtras_FortranParser08.java:33938)
	at fortran.ofp.parser.java.FortranParserExtras.module(FortranParserExtras.java:2930)
	at fortran.ofp.FrontEnd.parseModule(FrontEnd.java:120)
	at fortran.ofp.FrontEnd.parseProgramUnit(FrontEnd.java:199)
	at fortran.ofp.FrontEnd.call(FrontEnd.java:400)
	at fortran.ofp.FrontEnd.main(FrontEnd.java:349)
```

Part of the code where it fails:

```fortran
     DO i=1,iim
        DO j=1,jjm
           !
           IF (proj_stack(idom)%code /= PROJ_LATLON ) THEN  ! <-----HERE
              dx = proj_stack(idom)%dx
              ! Some projections in WRF do not store dy, in that case dy=dx.
              IF ( proj_stack(idom)%dy > 0 ) THEN
                 dy = proj_stack(idom)%dy
              ELSE
                 dy = proj_stack(idom)%dx
              ENDIF
              dxwrf(i,j) = dx/mapfac_x(i,j)
              dywrf(i,j) = dy/mapfac_y(i,j)
           ELSE
              !
              ! The LatLon projection is also a special case as here it is not the dx and dy
              ! which are stored in the projection file but the increments in Lon and Lat.
              !
              dtx = proj_stack(idom)%loninc
              dty = proj_stack(idom)%latinc
              coslat = COS(lat(j) * pi/180. )
              dxwrf(i,j) = dtx * pi/180. * R_Earth * coslat
              dywrf(i,j) = dty * pi/180. * R_Earth
              !
           ENDIF
           !
        ENDDO
     ENDDO
```

It seems It cannot handle a global variable inside the loop statement.

I include the last part of the XML output:
https://pastebin.com/tF4rCqCa

Complete code:
https://pastebin.com/fwk66WWk

**Comment by mbdevpl** [comment]
Fixed in latest release (0.4.0).

The file `test/examples_large/ORCHIDEE_grid.f90` is added as a test case for future compatibility.
