### ISSUE TITLE
do while statement

### ISSUE THREAD

**Issue by jurnix** [mbdevpl/open-fortran-parser-xml#4]
```
java fortran.ofp.FrontEnd --class fortran.ofp.XMLPrinter --output tree.xml --verbosity 100 src_sechiba/hydrolc.f90 
Cannot find any context of [loop] among open contexts.
Current context hierarchy (innermost first) is:
  statement
  body
  subroutine
  members
  module
  file
  ofp
java.lang.RuntimeException: Aborting construction of the AST.
	at fortran.ofp.XMLPrinter.cleanUpAfterError(XMLPrinter.java:2268)
	at fortran.ofp.XMLPrinter.contextFind(XMLPrinter.java:151)
	at fortran.ofp.XMLPrinter.setAttribute(XMLPrinter.java:305)
	at fortran.ofp.XMLPrinter.loop_control(XMLPrinter.java:1644)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.loop_control(FortranParserExtras_FortranParser08.java:25507)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.do_stmt(FortranParserExtras_FortranParser08.java:26778)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.block_do_construct(FortranParserExtras_FortranParser08.java:26646)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.do_construct(FortranParserExtras_FortranParser08.java:26616)
	at fortran.ofp.parser.java.FortranParserExtras.do_construct(FortranParserExtras.java:2855)
	at fortran.ofp.parser.java.FortranParserExtras.executable_construct(FortranParserExtras.java:630)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.execution_part_construct(FortranParserExtras_FortranParser08.java:1002)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.execution_part(FortranParserExtras_FortranParser08.java:803)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.subroutine_subprogram(FortranParserExtras_FortranParser08.java:39720)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.module_subprogram(FortranParserExtras_FortranParser08.java:34463)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.module_subprogram_part(FortranParserExtras_FortranParser08.java:34380)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.module(FortranParserExtras_FortranParser08.java:33938)
	at fortran.ofp.parser.java.FortranParserExtras.module(FortranParserExtras.java:2930)
	at fortran.ofp.FrontEnd.parseModule(FrontEnd.java:120)
	at fortran.ofp.FrontEnd.parseProgramUnit(FrontEnd.java:199)
	at fortran.ofp.FrontEnd.call(FrontEnd.java:400)
	at fortran.ofp.FrontEnd.main(FrontEnd.java:349)
```

Part of the code where it fails:
```fortran
     OnceMore = .TRUE.
     niter = 0
     lbad_ij(:)=.TRUE.
     DO WHILE ( OnceMore .AND. ( niter .LT. nitermax ) )  ! nitermax prevents infinite loops (should actually never occur)
       
       niter = niter + 1
```

Original source code:
https://pastebin.com/ytqC0z7i

**Comment by mbdevpl** [comment]
Fixed in latest release 0.4.0.

This case is added as `test/examples_large/ORCHIDEE_hydrolc.f90` for future compatibility.
