### ISSUE TITLE
if statement second operand error

### ISSUE THREAD

**Issue by jurnix** [mbdevpl/open-fortran-parser-xml#6]
It seems there is an issue with the second part of the conditional statement:

```fortran
IF (map_pft_format .AND. .NOT. impveg) THEN
```

Error message:
```bash
java fortran.ofp.FrontEnd --class fortran.ofp.XMLPrinter --output tree.xml --verbosity 100 src_sechiba/slowproc.f90 
Cannot rename current context from 'statement' to 'if' because it has unexpected name 'operand'.
java.lang.RuntimeException: Aborting construction of the AST.
	at fortran.ofp.XMLPrinter.cleanUpAfterError(XMLPrinter.java:2598)
	at fortran.ofp.XMLPrinter.contextRename(XMLPrinter.java:181)
	at fortran.ofp.XMLPrinter.contextRename(XMLPrinter.java:187)
	at fortran.ofp.XMLPrinter.if_then_stmt(XMLPrinter.java:1655)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.if_then_stmt(FortranParserExtras_FortranParser08.java:22659)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.if_construct(FortranParserExtras_FortranParser08.java:22446)
	at fortran.ofp.parser.java.FortranParserExtras.if_construct(FortranParserExtras.java:2979)
	at fortran.ofp.parser.java.FortranParserExtras.executable_construct(FortranParserExtras.java:652)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.execution_part_construct(FortranParserExtras_FortranParser08.java:1002)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.execution_part(FortranParserExtras_FortranParser08.java:803)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.subroutine_subprogram(FortranParserExtras_FortranParser08.java:39720)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.module_subprogram(FortranParserExtras_FortranParser08.java:34463)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.module_subprogram_part(FortranParserExtras_FortranParser08.java:34380)
	at fortran.ofp.parser.java.FortranParserExtras_FortranParser08.module(FortranParserExtras_FortranParser08.java:33938)
	at fortran.ofp.parser.java.FortranParserExtras.module(FortranParserExtras.java:2930)
	at fortran.ofp.FrontEnd.parseModule(FrontEnd.java:120)
	at fortran.ofp.FrontEnd.parseProgramUnit(FrontEnd.java:199)
	at fortran.ofp.FrontEnd.call(FrontEnd.java:400)
	at fortran.ofp.FrontEnd.main(FrontEnd.java:349)
```

**Comment by mbdevpl** [comment]
Fixed in latest release 0.4.0. This test case is added as `test/examples/simple_if.f90`.
